const postId = '3e6b15dc-08bb-4d8a-afa7-e40813f4e4d9';
const url = `https://mytaxbot-linkedin.a-lopezalon91.workers.dev/api/posts/${postId}/regenerate-carousel`;

// We need to fetch the content_edited first, or we can just read it from our previous local text.
const text = `La asunción del cargo de administrador en una sociedad en crisis estructural es una trampa mortal si no se audita el pasado con precisión quirúrgica. ⚠️\n\nLa reciente Sentencia del Tribunal Supremo 323/2026 marca una línea roja vital sobre la derivación de responsabilidad por deudas societarias. Un administrador entrante que acepta el cargo en una mercantil que ya se encuentra en causa legal de disolución no puede ser condenado a pagar de su bolsillo las deudas que nacieron antes de su nombramiento. El alto tribunal fulmina así la aplicación extensiva y casi automática de la presunción del artículo 367.2 de la Ley de Sociedades de Capital que aplicaban algunos juzgados de lo mercantil.\n\n1️⃣ Escenario de entrada en sociedad zombi: Si asumes la administración de una entidad y descubres que su patrimonio neto está por debajo de la mitad del capital social, la ley te obliga a convocar junta en dos meses. Si incumples, respondes solidariamente. Sin embargo, bajo esta nueva doctrina, si un proveedor te reclama facturas impagadas del ejercicio anterior, tu patrimonio personal queda a salvo porque dichas obligaciones son cronológicamente previas a tu gestión.\n\n2️⃣ Escenario de presunción probatoria inversa: El acreedor siempre intentará utilizar el artículo 367.2 LSC para presumir legalmente que sus créditos nacieron después de tu nombramiento. No obstante, si logras acreditar de forma documental que las facturas tienen fecha anterior a tu aceptación del cargo, esta presunción 'iuris tantum' se desactiva instantáneamente, blindando tu posición como nuevo administrador frente a pasivos heredados.\n\nEste pronunciamiento no es un hecho aislado, sino la consolidación definitiva de la doctrina marcada anteriormente por la STS 601/2019 y la STS 144/2017. Además, el Supremo armoniza inteligentemente su fallo con la reciente reforma introducida por la Ley 16/2022, la cual positivizó esta misma jurisprudencia añadiendo el nuevo artículo 367.3 LSC. Dicho precepto aclara sin margen de duda que el contador temporal de responsabilidad civil arranca exclusivamente desde la aceptación formal del cargo directivo.\n\nA nivel estratégico, esta resolución otorga una seguridad jurídica incalculable a los profesionales de la reestructuración corporativa que entran para reflotar empresas al borde del concurso de acreedores. Exige, eso sí, una diligencia preventiva extrema: la fecha exacta de inscripción en el Registro Mercantil y la auditoría forense de la deuda se convierten en el único escudo válido.\n\n¿Cómo afectará esta jurisprudencia a tu próxima auditoría de riesgos antes de aceptar un cargo directivo?\n\n#DerechoMercantil #ResponsabilidadAdministradores #Jurisprudencia #ComplianceLegal #TribunalSupremo`;

fetch(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({ content_edited: text })
})
.then(res => res.json())
.then(data => console.log('Success:', data))
.catch(err => console.error('Error:', err));
